theme: jekyll-theme-minimal
title: Sanket Desai's Profile
logo: /assets/img/DP.jpg
show_downloads: true
google_analytics:
name: Sanket Desai 
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
