theme: jekyll-theme-Modernist
title: Sanket Desai's Profile
description: Bookmark this to keep an eye on my project updates!
name: Sanket Desai 
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
